config/routes.rb
MusicApp::Application.routes.draw do
  resources :bands do
      resources :albums, only: :index
  end

  resources :albums, except: :index do
    resources :tracks, only: :index
  end
  resources :tracks, except: :index
  resources :users

  get 'users/:id/activate' => 'users#activate', as: "users_activate"
  put 'users/authenticate' => 'users#authenticate', as: "users_authenticate"

  get 'bands/:id/tracks' => 'bands#tracks', as: "bands_tracks"
  post 'track/:id/note' => 'tracks#add_note', as: "add_note"
  delete 'track/note/:id' => 'tracks#delete_note', as: "delete_note"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :genre, :recorded, :band_id

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums

  validates :name, presence: true, uniqueness: true

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :track_id, :body

  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name, :track_num, :album_id, :band_id, :kind, :lyrics

  belongs_to :album
  has_one :band, through: :album
  has_many :notes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :status, :user_token

  validate :email, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @band = Band.find(params[:band_id])
    @albums = @band.albums
    render :index
  end

  def create
    band_id = Band.find_by_name(params[:band][:name]).id
    params[:album][:band_id] = band_id
    album = Album.new(params[:album])

    flash[:errors] ||= []

    if album.save
      redirect_to band_albums_url(band_id)
    else
      flash[:errors] << "Could not create album"
    end
  end

  def new
    @bands = Band.all
    render :new
  end

  def edit
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    @bands = Band.all
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    render :show
  end

  def update
    band_id = Band.find_by_name(params[:band][:name]).id
    params[:album][:band_id] = band_id

    album = Album.find(params[:id])
    album.update_attributes(params[:album])

    flash[:errors] ||= []
    if album.save
      redirect_to band_albums_url(band_id)
    else
      flash[:errors] << "Could not update band"
    end
  end

  def destroy
    @album = Album.find(params[:id])
    band_id = @album.band.id
    @album.destroy
    redirect_to band_albums_url(band_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :validate_login


  def validate_login
    unless logged_in?
      flash[:errors] ||= []
      flash[:errors] << "Not authorized for this section"
      redirect_to users_url
    end
  end

  def current_user
    @current_user ||= User.find_by_user_token(session[:token])
  end

  def logged_in?
      !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    band = Band.new(params[:band])
    flash[:errors] ||= []

    if band.save
      redirect_to bands_url
    else
      flash[:errors] << "Could not create band"
    end
  end

  def new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    band = Band.find(params[:id])
    band.update_attributes(params[:band])
    flash[:errors] ||= []

    if band.save
      redirect_to band_url
    else
      flash[:errors] << "Could not update band"
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def tracks
    @band = Band.find(params[:id])
    render :tracks
  end
end

app/controllers/tacks_controller.rb
class TacksController < ApplicationController
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @album = Album.find(params[:album_id])
    @band = @album.band
    render :index
  end

  def create
    album = Album.find_by_name(params[:album][:name])
    band_id = album.band_id
    params[:track][:album_id] = album.id
    params[:track][:band_id] = band_id
    track = Track.new(params[:track])
    flash[:errors] ||= []

    if track.save
      redirect_to album_tracks_url(album.id)
    else
      flash[:errors] << "Could not create track"
    end
  end

  def new
    @albums = Album.all
    render :new
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    @band = @album.band
    render :show
  end

  def update
    album = Album.find_by_name(params[:album][:name])
    band_id = album.band_id
    params[:track][:album_id] = album.id
    params[:track][:band_id] = band_id

    track = Track.find(params[:id])
    track.update_attributes(params[:track])
    flash[:errors] ||= []

    if track.save
      redirect_to album_tracks_url(album.id)
    else
      flash[:errors] << "Could not create track"
    end

  end

  def destroy
    track = Track.find(params[:id])
    album_id = track.album_id
    track.destroy
    redirect_to album_tracks_url(album_id)
  end

  def add_note
    params[:note][:track_id] = params[:id]
    note = Note.new(params[:note])
    flash[:errors] ||= []

    if note.save
      redirect_to track_url(params[:id])
    else
      flash[:errors] << "Could not create note"
    end
  end


  def delete_note
    note = Note.find(params[:id])
    track_id = note.track_id
    note.destroy
    redirect_to track_url(track_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SecureRandom

  skip_before_filter :validate_login, :authenticate
  def index
    render :login
  end

  def authenticate
    temp_user = User.find_by_email(params[:user][:email])
    flash[:errors] ||= []

    if temp_user.password == params[:user][:password]
      temp_user.user_token = SecureRandom.base64
      session[:token] = temp_user.user_token
      redirect_to bands_url
    else
      flash[:errors] << "incorrect password"
    end
  end

  def new
    render :new
  end

  def create
    user = User.new(params[:user])
    flash[:errors] ||= []

    if user.save
      user.user_token = SecureRandom.base64
      msg = UserMailer.activation_email(user)
      msg.deliver!
      flash[:errors] << "Please click activation link in your email"
      redirect_to users_url
    else
      flash[:errors] << "Could not create account"
    end

  end

  def destroy

  end

  def activate
    user = User.find(params[:id])
    flash[:errors] ||= []
    if user.user_token == params[:token]
      user.status = "activated"
    else
      flash[:errors] << "Not your token"
    end
    if user.save
      render :login
    else
      flash[:errors] << "Something went wrong"
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/tacks_helper.rb
module TacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <div>Name: <input type="text" name="album[name]" value="<%= @album.name %>"></div>

  <div>Genre: <input type="text" name="album[genre]" value="<%= @album.genre %>"></div>

  <div>Band:
    <select name="band[name]">
      <option ><%= @band.name %></option>
      <% @bands.each do |band| %>
      <option value="<%= band.name %>"><%= band.name %></option>
      <% end %>
    </select>
  </div>

  <div>
    Recorded:
    <input name="album[recorded]" id="studio_recorded" type="radio" value="studio"
      <%= @album.recorded == "studio" ? "checked" : "" %>>
    <label for="studio_recorded">Studio</label>

    <input name="album[recorded]" id="live_recorded" type="radio" value="live"
    <%= @album.recorded == "live" ? "checked" : "" %>>
    <label for="live_recorded">Live</label>
  </div>

  <br>
  <input type="submit" value="Submit">
</form>

app/views/albums/index.html.erb
<h1><%= @band.name %>'s Albums Page!</h1>

<ul>
  <% @albums.each do |album| %>

  <li>
    <a href="<%= album_url(album) %>"><%= album.name %></a>
  </li>
  <br>

  <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Create Album</h1>

<form action="<%= albums_url %>" method="post">
  <div>Name: <input type="text" name="album[name]"></div>

  <div>Genre: <input type="text" name="album[genre]"></div>

  <div>Band:
    <select name="band[name]">
      <option value="">Choose a band</option>
      <% @bands.each do |band| %>
      <option value="<%= band.name %>"><%= band.name %></option>
      <% end %>
    </select>
  </div>

  <div>
    Recorded:
    <input name="album[recorded]" id="studio_recorded" type="radio" value="studio">
    <label for="studio_recorded">Studio</label>

    <input name="album[recorded]" id="live_recorded" type="radio" value="live">
    <label for="live_recorded">Live</label>
  </div>

  <br>
  <input type="submit" value="Submit">
</form>

app/views/albums/show.html.erb
<h1> <%= @album.name %></h1>
<a href="<%= band_url(@band) %>"><%= @band.name %></a>
<br>
<a href="<%= album_tracks_url(@album) %>">Tracks</a>
<br>
<form action="<%= edit_album_url(@album) %>" method="get">
  <input type="submit" value="Edit album">
</form>
<br>
<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Remove album">
</form>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <div>
    Band name: <input type="text" name="band[name]" value="<%= @band.name %>">
  </div>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/bands/index.html.erb
<h1>Bands Page!</h1>

<ul>
  <% @bands.each do |band| %>

  <li> <a href="<%= band_url(band) %>"><%= band.name %></a>
    <ul>
      <li><a href="<%= band_albums_url(band) %>">Albums</a></li>
      <li><a href="<%= bands_tracks_url(band) %>">Tracks</a></li>
    </ul>
  </li>
  <br>

  <% end %>
</ul>

<form action="<%= new_band_url %>" method="get">
  <input type="submit" value="Create band">
</form>
<br>

<form action="<%= new_album_url %>" method="get">
  <input type="submit" value="Create album">
</form>

<br>
<form action="<%= new_track_url %>" method="get">
  <input type="submit" value="Add track">
</form>

app/views/bands/new.html.erb
<h1>Create Band</h1>

<form action="<%= bands_url %>" method="post">
  <div>Band name: <input type="text" name="band[name]"></div>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/bands/show.html.erb
<h1> <%= @band.name %>'s page</h1>

<a href="<%= band_albums_url(@band) %>">Albums</a>
<br>
<a href="<%= bands_tracks_url(@band) %>">Tracks</a>

<p>
  <form action="<%= edit_band_url(@band)%>" method="get">
    <input type="submit" value="Edit band">
  </form>
  <form action="<%= band_url(@band)%>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Remove band">
  </form>
</p>

app/views/bands/tracks.html.erb
<h1><%= @band.name  %>'s Tracks </h1>

<ul>
  <% @band.albums.each do |album| %>
    <li>
      <a href="<%= album_url(album) %>"><%= album.name %></a>
      <ol>
        <% album.tracks.each do |track| %>
        <li><a href="<%= track_url(track) %>"><%= track.name %></a></li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash[:errors].try(:each) do |msg| %>
     <%= msg %>
   <% end %>

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<% @track.notes.each do |note| %>
  <%= note.body  %>
  <form action="<%= delete_note_url(note) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Remove note">
  </form>
<% end %>

app/views/tracks/edit.html.erb
<h1>Edit <%= @track.name %></h1>

<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="put">

  <div>Name: <input type="text" name="track[name]" value="<%= @track.name %>"></div>

  <div>Album:
    <select name="album[name]">
      <option value="<%= @track.album.name %>"><%= @track.album.name %></option>
      <% @albums.each do |album| %>
      <option value="<%= album.name %>"><%= album.name %></option>
      <% end %>
    </select>
  </div>

  <div>
    Type:
    <input name="track[kind]" id="regular_track" type="radio" value="regular"
      <%= @track.kind == "regular" ? "checked" : "" %>>
    <label for="regular_track">Regular</label>

    <input name="track[kind]" id="bonues_track" type="radio" value="bonus"
      <%= @track.kind == "bonus" ? "checked" : "" %>>
    <label for="bonus_track">Bonus</label>
  </div>
  <br>
  <div>Lyrics:<br>
    <textarea cols="30" rows="4" name="track[lyrics]"><%= @track.lyrics %></textarea>
  </div>

  <br>
  <input type="submit" value="Submit">
</form>

app/views/tracks/index.html.erb
<h1><%= @album.name %> Tracks Page!</h1>

<ol>
  <% @album.tracks.each do |track| %>

  <li>
    <a href="<%= track_url(track) %>"><%= track.name %></a>
  </li>
  <br>

  <% end %>
</ol>

app/views/tracks/new.html.erb
<h1>Create Track</h1>

<form action="<%= tracks_url %>" method="post">
  <div>Name: <input type="text" name="track[name]"></div>

  <div>Album:
    <select name="album[name]">
      <option value="">Choose an album</option>
      <% @albums.each do |album| %>
      <option value="<%= album.name %>"><%= album.name %></option>
      <% end %>
    </select>
  </div>

  <div>
    Type:
    <input name="track[kind]" id="regular_track" type="radio" value="regular">
    <label for="regular_track">Regular</label>

    <input name="track[kind]" id="bonues_track" type="radio" value="bonus">
    <label for="bonus_track">Bonus</label>
  </div>
  <br>
  <div>Lyrics:<br>
    <textarea cols="30" rows="4" name="track[lyrics]"></textarea>
  </div>

  <br>
  <input type="submit" value="Submit">
</form>

app/views/tracks/show.html.erb
<h1> <%= @track.name %></h1>
<a href="<%= band_url(@band) %>"><%= @band.name %></a>
<br>
<a href="<%= album_url(@album) %>"><%= @album.name %></a>
<br>
<form action="<%= edit_track_url(@track) %>" method="get">
  <input type="submit" value="Edit track">
</form>
<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Remove track">
</form>

<form action="<%= add_note_url(@track) %>" method="post">
  <div>Add Note:<br>
    <textarea cols="30" rows="4" name="note[body]"></textarea>
  </div>
  <input type="submit" value="Submit">
</form>


<br>
<%= render :partial => "notes/note" %>
<br>

app/views/users/login.html.erb
<h1>Login</h1>

<form action="<%= users_authenticate_url %>" method="post">
  <input type="hidden" name="_method" value="put">
  <div>Email: <input type="email" name="user[email]"></div>
  <div>Password: <input type="password" name="user[password]"></div>
  <input type="submit" value="Login">
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <div>Email: <input type="email" name="user[email]"></div>
  <div>Password: <input type="password" name="user[password]"></div>
  <input type="submit" value="Submit">
</form>